# for every variable the "overridable" flag is default TRUE
version: 1.0
phases:
  project_start:
    max. no of failed tests: 
      overridable: false
      value: falling # It shall be possible to use keywords "falling" or "raising" to check the progress per push, pull request(?) and release (?)
    max. no of skipped tests: 
      value: falling # if limit is not need then it shall not be defined in config
  before_sop:
    overridable: false
    max. no of failed tests: 
      value: 10
    max. no of skipped tests: 
      value: 0
