# for every variable the "overridable" flag is default TRUE
version: 1.0
phases:
  project_start:
    gtest_validator:
      max. no of failed tests: 
        value: falling # It shall be possible to use keywords "falling" or "raising" to check the progress per push, pull request(?) and release (?)
      max. no of skipped tests: 
        value: 30 # if limit is not need then it shall not be defined in config
  before_sop:
    max. no of failed tests:
      overridable: false # this is only for this variables
      value: 0
    max. no of skipped tests:
      value: 2
  after_sop:
    overridable: false
    max. no of failed tests: 
      value: 0
    max. no of skipped tests: 
      value: 0
